name: null
favicon: null
layout_spectrum: 0.16667
typography_spectrum: 0.21053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#783bbd'
    - '#ffffff'
    - '#e22d2c'
    - '#222222'
    - '#9b9b9b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: null
    url: null
