name: null
favicon: null
layout_spectrum: 0.26316
typography_spectrum: 0.71053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1d1c'
    - '#f2f1f6'
    - '#cbcbcb'
    - '#888789'
    - '#4e4e4d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: a4159772-ac4b-4ed4-b029-e800c249ea1a
    url: null
