cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.8125
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#1e1d1c'
    - '#f2f1f6'
    - '#cbcbcb'
    - '#888789'
    - '#4e4e4d'
  lightness: 1
purpose:
  - name: follow
    url: null
    item: a4159772-ac4b-4ed4-b029-e800c249ea1a
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0.10848
typography_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
name: velloff
