name: null
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.71053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#526367'
    - '#9ba79d'
    - '#eae9e4'
    - '#2a2a2a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: null
    url: null
